enum AirplaneSprites {
  AIRPLANE_TRASH_EMPTY = 964, 
  AIRPLANE_TRASH_FULL = 963,
  AIRPLANE_CABINET_EMPTY = 966,
  AIRPLANE_CABINET_FULL = 965, 
  
  FIRST_AIT_KIT = 989, 
  
  BATHROOM_HANDLE_UP = 442, 
  BATHROOM_HANDLE_SIDE = 445, 
  
  BATHROOM_CORD = 1076,
  BATHROOM_CORD_W_THREAD = 480,
  BATHROOM_CORD_W_THREAD_HANDLE_TAUT = 558,
  BATHROOM_CORD_W_THREAD_HANDLE_LOOSE = 1184, 
  
  BATHROOM_SIGN_ON = 1075, 
  BATHROOM_SIGN_OFF = 1074
};