enum ClaraViews {
  CLARA_NORMAL = 2,
  CLARA_IDLE = 3, 
  CLARA_SIT = 10,
  CLARA_FALL = 12,
  CLARA_FIRST_AID_KIT = 13,
  CLARA_BATHROOM = 14, 
  CLARA_BATHROOM_THREAD_A = 15,
  CLARA_BATHROOM_THREAD_B = 16,
  CLARA_MAIN_CABIN = 28
};