import bool IsOverWalkableArea(static Mouse);
import bool IsOverHotspot(static Mouse);
import bool IsOverCharacter(static Mouse);
import bool IsOverObject(static Mouse);
import bool IsOverNothing(static Mouse);
import Hotspot* GetOverHotspot(static Mouse);
import Character* GetOverCharacter(static Mouse);
import Object* GetOverObject(static Mouse);
import int GetWalkableArea(static Mouse);